owner: thundersquared
repo: upptime

sites:
  - name: thundersquared
    url: https://thundersquared.com/
  - name: web1
    url: $UPTIME_SITE_1
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: web2
    url: $UPTIME_SITE_2
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: web4
    url: $UPTIME_SITE_4
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: web5
    url: $UPTIME_SITE_5
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: web6
    url: $UPTIME_SITE_6
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: web7
    url: $UPTIME_SITE_7
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200

assignees:
  - anatolinicolae
  
status-website:
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  robotsText: "User-agent: * \n Disallow: /"
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime).
  navbar:
    - title: Status 1
      href: /
    - title: Status 2
      href: https://status.thundersquared.com/
    - title: thundersquared
      href: https://thundersquared.com/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
